### ISSUE TITLE
Regions of Ukraine

### ISSUE THREAD

**Issue by andkov** [kse-ua/ua-de-center#13]
@izasimovych could you please help me group oblasts into 5–6 larger regions? E.g. west, center, northeast, east, south, crimea. Or some thing that makes more sense to you in the context of our analysis.

**Comment by Tytser** [comment]
If I can intervene in this issue, I would suggest the following composition of macroregions (I used it for stratification in nationwide surveys):
- West: Закарпатська, Чернівецька, Львівська, Івано-Франківська, Тернопільська, Волинська, Рівненська
- Center: Хмельницька, Вінницька, Черкаська, Кіровоградська, Полтавська
- North: Житомирська, Київська, м.Київ, Чернігівська, Сумська
- South: Одеська, Миколаївська, Херсонська
- East: Харківська, Донецька, Луганська, Дніпропетровська, Запорізька (also can be used in South)

We can leave Crimea as a separate entity since it didn't take part in the decentralization processes due to annexation

**Comment by andkov** [comment]
@Tytser , thank you! That’s just what I had in mind.
